#include<stdio.h>
int main(){
    char ch = 'a';// HERE WE HAVE USED CHARATER DATATYPE WHICH IS USED FOR STORING "A","a",/,{},=,>,< AND MORE
    printf("%c",ch);// WE USE %C FOR FETCHING THE VALUE OF CHARACTER DATATYPE
    return 0;
}
// printf("%c",ch); HERE IN PLACE OF %C IF WE HAVE USED %D THEN THE RESULTED OUTPUT WILL BE THE CHARACTERS ASCII 
// VALUE AS A=65,B=66,C=67,D=68......SO ON
// a=97,b=66,c=67,d=68,e=69.......SO ON AND SPECIAL CHARACTER ALSO HAVE ASCII VALUE AS #=35,!=33 ETC.