#include<stdio.h>
int main(){
    char str[]="CODING IS REALLY PROBLEM SOLVING USING SKILLS";
    puts(str);// HERE IT IS PRINTING STRING WITHOUT FORMAT SPECIFIER USING PUTS FUNCTION

    puts("HELLO EVERYONE");// HERE IT IS WORKING SAME AS A PRINTF STATEMENT FUNCTION OR
    return 0;// IT IS A OUTPUT FUNCTION OF STRING
}