#include<stdio.h>
int main(){
    float n;
    printf("ENTER A NUMBER:");
    scanf("%f",&n);
    if(n>99 && n<1000){// WE HAVE USED AND(&) LOGICAL OPERATOR 
    printf("THE ENTERED NUMBER IS A THREE DIGIT NUMBER");
    }
    else{
        printf("IT IS NOT A THREE DIGIT NUMBER");
    }
    return 0;
}// THIS OPERATOR WILL RUN THE CODE INSIDE IF WHEN BOTH THE CONDITION WILL GET SATISFIED
//  AS AND OPERATOR NEED TO HAVE ALL CONDITONS SATISFIED AND IF ONE OR BOTH CONDITION 
//  NOT GET SATISFIED THEN ELSE PART WILL GET EXECUTED.