#include<stdio.h>// THE CODE WILL REMAIN THE SAME BUT AT THE OUTPUT SCREEN WHEN WE WILL
int main() {// ENTER B>A THEN IT WILL GIVE DIVIDENT AS OUTPUT BECAUSE WHEN WE GIVE B>A THEN
    int a,b,remainder;// THE SYSTEM DO NOT DIVIDE THE NUMBER COMPLETELY AS THE QUOTIENT IS 
    printf("ENTER DIVIDENT:");//APPROXIMATELY 0 U CAN DIVIDE A NUMBER WITH THE SAME CONDITION 
    scanf("%d",&a);//IN NOTEBOOK FOR BETTER UNDERSTANDING OF HOW IT IS FETCHING 1 REMAINDER HERE
    printf("ENTER DIVISOR:");
    scanf("%d",&b);
    remainder = a%b;
    printf("WHEN %d IS DIVIDED WITH %d THEN REMAINDER IS:%d",a,b,remainder);
    return 0;
}